// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoBoothApi.Models;

#nullable disable

namespace PhotoBoothApi.Migrations
{
    [DbContext(typeof(PhotoBoothApiContext))]
    [Migration("20240223175705_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PhotoBoothApi.Models.Booth", b =>
                {
                    b.Property<int>("BoothId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("BoothId");

                    b.ToTable("Booths");

                    b.HasData(
                        new
                        {
                            BoothId = 1,
                            Address = "435 N Killingsworth St, Portland, OR 97217",
                            Color = "Both",
                            Location = "The Florida Room",
                            Neighborhood = "NE",
                            Type = "Digital"
                        },
                        new
                        {
                            BoothId = 2,
                            Address = "1026 SW Harvey Milk St, Portland, OR 97205",
                            Color = "B&W",
                            Location = "Stumptown Coffee",
                            Neighborhood = "SW",
                            Type = "Film"
                        },
                        new
                        {
                            BoothId = 3,
                            Address = "1829 NE Alberta St ste c, Portland, OR 9721",
                            Color = "Both",
                            Location = "Psychic Sister",
                            Neighborhood = "NE",
                            Type = "Digital"
                        },
                        new
                        {
                            BoothId = 4,
                            Address = "4800 SE Hawthorne Blvd, Portland, OR 97215",
                            Color = "Both",
                            Location = "Space Room Lounge",
                            Neighborhood = "SE",
                            Type = "Digital"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
